// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollEffects from "./ScrollEffects";
import { bebas, barlow } from './fonts'
import Header from "@/components/ui/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${bebas.variable} ${barlow.variable}`}>
      <body className={`${bebas.variable} ${barlow.variable}`}>
        <ScrollEffects />
        <Header />
        {children}
      </body>
    </html>
  );
}
